from django.urls import path,include
from .import views
from rest_framework.routers import DefaultRouter
# Tocken is generated by client
from rest_framework.authtoken.views import obtain_auth_token

# Create router object
router = DefaultRouter()

# Register router with StudentModelViewSet

router.register('StudentAPI',views.StudentModelViewSet,basename='student')


# Here we don't need to mentioned :- path('studentdetail/<int:pk>',views.StudentRetrieveUpdateDelete.as_view())
    # url here ,because it automatically handle pk value.

urlpatterns = [
    path('router/',include(router.urls)),
    path('gettoken/',obtain_auth_token),
    
]

# Tocken is generated by Admin with the help of Terminal:
#  Write below line in the terminal and run it.
# python3 manage.py drf_create_token username-->write user name here



# Tocken is generated by client : FOLLOW this method:
# Write below line in the terminal and run it.
# http POST http://127.0.0.1:8000/myapp/gettoken/ username="Dhruvil" password="admin123"
# After we get token in json format:
   #   {
   # "token": "d3ddd62886168991205286199dc15c593520dbff"
   #   }